<a href="https://colab.research.google.com/github/karthik151102/British-Airways-Good-or-Bad/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Deep Learning Week 1 Programs
#1.Write a Program to demonstrate scalar and vector of tensors using numpy and apply key attributes(rank, shape and dtype on each type of tensor).
#1a. scalar or 0D tensor
import numpy as np
x=np.array(10)
print(x)
print("Dimension of x is",x.ndim)
print("Shape of x is",x.shape)
print("Data type of x is ",x.dtype)

10
Dimension of x is 0
Shape of x is ()
Data type of x is  int64


In [ ]:
#1b.Vector or 1D tensor
import numpy as np
x=np.array([1,2,3,4])
print(x)
print("Dimension of x is",x.ndim)
print("Shape of x is",x.shape)
print("Data type of x is ",x.dtype)

[1 2 3 4]
Dimension of x is 1
Shape of x is (4,)
Data type of x is  int64


In [ ]:
#2. Write a Program to demonstrate Matrix and Rank 3 tensors using numpy and apply key attributes(rank, shape and dtype on each type of tensor).
#2a.Matrix or 2D tensor

import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print("Dimension of x is",x.ndim)
print("Shape of x is",x.shape)
print("Data type of x is ",x.dtype)

[[1 2 3 4]
 [5 6 7 8]]
Dimension of x is 2
Shape of x is (2, 4)
Data type of x is  int64


In [ ]:
#2b.  3D tensor or high dimensional tensor
import numpy as np
x=np.array([[[1,2,3,4],[5,6,7,8]],[[1,1,1,1],[2,2,2,2]]])
print(x)
print("Dimension of x is",x.ndim)
print("Shape of x is",x.shape)
print("Data type of x is ",x.dtype)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 1 1 1]
  [2 2 2 2]]]
Dimension of x is 3
Shape of x is (2, 2, 4)
Data type of x is  int64


In [ ]:
#3. Write a program to demonstrate Tensor slicing for manipulating tensor

#loading mnist dataset
from tensorflow.keras.datasets import mnist
(train_images, train_labels),(test_images, test_labels) = mnist.load_data()


In [ ]:
print("MNIST DataSet")
print("**************")
print("Trained images dimension is",train_images.ndim)
print("Trained images shape is",train_images.shape)
print("Tained images datatype is",test_images.dtype)
print("Train labels dimension is",train_labels.ndim)
print("Train labels shape is",train_labels.shape)
print()
print("Test images dimension  is ",test_images.ndim)
print("Test images shape is ",test_images.shape)
print("Test labels dimension is",test_labels.ndim)
print("Test labels shape is",test_labels.shape)
print()

MNIST DataSet
**************
Trained images dimension is 3
Trained images shape is (60000, 28, 28)
Tained images datatype is uint8
Train labels dimension is 1
Train labels shape is (60000,)

Test images dimension  is  3
Test images shape is  (10000, 28, 28)
Test labels dimension is 1
Test labels shape is (10000,)



In [ ]:
#manipulating tensors on mnist dataset or tensor slicing operation

#To select digits #10 to #100 (#100 isn’t included)

slice1 = train_images[10:100]
print(slice1.shape)
'''Above slicing is equivalent to which specifies a start index and stop index for the  slice along each tensor axis. Note that : is equivalent to selecting the  entire axis'''
slice1 = train_images[10:100,:,:]
print(slice1.shape) #This statement also equivalent to the above examples
slice1 = train_images[10:100,0:28,0:28]
print(slice1.shape) #To select 14 X 14 pixels in the bottom-right corner of all images
slice1 = train_images[:,:14,:14]
print(slice1.shape) #To crop the images to patches of 14 X 14 pixels centered in the middle
slice1 = train_images[:,7:-7,7:-7]
print(slice1.shape)

(90, 28, 28)
(90, 28, 28)
(90, 28, 28)
(60000, 14, 14)
(60000, 14, 14)
